# Generated by Django 6.0.3 on 2026-04-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyerportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
